### ISSUE TITLE
Add a news line (news ticker) running above/below the chart component

### ISSUE THREAD

**Issue by Arivadis** [Arivadis/BitsHit#6]
Needed the news ticker running below/above the chart compnent (better sticked to it).

What the news? Currently does not metter. Can be fake, or real, statick or from any open API.

Feel free to ask any questions.

**Comment by Ananta2003** [comment]
Hey! I’ve solved the ticker issue and just made a pull request. Feel free to check it out and merge when ready. 👍

**Comment by Arivadis** [comment]
> ###
> [Aug 23, 2024](#issuecomment-2307551755)

Hello!

Comming back to the project.
I remember there was the pull-request - did you remove it?

**Comment by Arivadis** [comment]
Made properly, good work
